# Generated by Django 4.2.1 on 2023-06-13 07:00

from django.db import migrations, models
import django.db.models.deletion

def get_default_job_type(apps, schema_editor):
    JobType = apps.get_model('first', 'job_type')
    default_job_type = JobType.objects.first
    return default_job_type
    

class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_managesalary_employee_managesalary_job_type'),
    ]

    operations = [
        
    migrations.RunPython(get_default_job_type),
        migrations.AlterField(
            model_name='dailywork',
            name='job_type',
            field=models.ForeignKey(default=get_default_job_type,on_delete=django.db.models.deletion.CASCADE, to='first.job_type')
           
        ),
    ]
