# Generated by Django 4.2.1 on 2023-06-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0021_rename_job_type_dailywork_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailywork',
            name='Task',
        ),
        migrations.AddField(
            model_name='dailywork',
            name='job_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.job_type'),
            preserve_default=False,
        ),
    ]
